=== OceanOPS/oceanjson/schemas/platform.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"properties": {
	  "platform_id": {
		"type": "integer"
	  },
	  "platform_ref": {
		"type": "string"
	  },
	  "platform_program": {
		"type": "object",
		"properties": {
		  "program_id": { "type": "integer" },
		  "program_name": { "type": "string" },
		  "program_description": { "type": "string" },
		  "program_country": { "$ref": "#/definitions/country" },
		  "program_name_short": { "type": "string" },
		  "program_wigos_code": { "type": "string" },
		  "program_network": { "$ref": "#/definitions/network" }
		}
	  },
	  "platform_project": { "type": "string" },
	  "platform_site": {
		"type": "object",
		"properties": {
		  "site_id": { "type": "integer" },
		  "site_name": { "type": "string" },
		  "site_description": { "type": "string" }
		}
	  },
	  "platform_name": { "type": "string" },
	  "platform_parent_ref": { "type": "string" },
	  "platform_activity_criterion": { "type": "integer" },
	  "platform_closure_criterion": { "type": "integer" },
	  "platform_class_categories": { "type": "array" },
	  "platform_area": { "type": "array" },
	  "platform_services": { "type": "array" },
	  "platform_networks": { 
		"type": "array",
		"items": { "$ref": "#/definitions/network" }
		},
	  "platform_sub_networks": { 
		"type": "array" ,
		"items": { "$ref": "#/definitions/network" }
		},
	  "platform_all_networks": {
		"type": "array",
		"items": { "$ref": "#/definitions/network" }
	  },
	  "platform_model": { "$ref": "#/definitions/platform_model" },
	  "platform_owner": { "type": "object" },
	  "platform_service_schedule": { "type": "object" },
	  "platform_principal_investigator": { "type": "object" },
	  "platform_operating_agency": { "type": "object" },
	  "platform_dac": { "type": "object" },
	  "platform_end_date": { "type": "string" },
	  "platform_deployment": {
		"type": "object",
		"properties": {
		  "deployment_method": {
			"type": "object",
			"properties": {
			  "method_id": { "type": "integer" },
			  "method_name": { "type": "string" },
			  "method_description": { "type": "string" }
			}
		  },
		  "deployment_country": { "$ref": "#/definitions/country" },
		  "deployment_latitude": { "type": ["number", "null"] },
		  "deployment_longitude": { "type": ["number", "null"] },
		  "deployment_height": { "type": ["number", "null"] },
		  "deployment_date": { "type": "string" },
		  "deployment_ship": { "$ref": "#/definitions/ship" },
		  "deployment_cruise": { "$ref": "#/definitions/cruise" },
		  "ref_station_id": { "type": "string" },
		  "no_site": { "type": "boolean" },
		  "max_mooring_depth": { "type": ["number", "null"] },
		  "deployment_operator": { "type": "object" }
		}
	  },
	  "platform_retrieval": {
		"type": "object",
		"properties": {
		  "retrieval_status": { "type": "object" },
		  "post_retrieval_status": { "type": "object" },
		  "retrieval_latitude": { "type": ["number", "null"] },
		  "retrieval_longitude": { "type": ["number", "null"] },
		  "retrieval_start_date": { "type": "string" },
		  "retrieval_end_date": { "type": "string" },
		  "retrieval_country": { "$ref": "#/definitions/country" },
		  "platform_ending_cause": {
			"type": "object",
			"properties": {
			  "ending_cause_id": { "type": "integer" },
			  "ending_cause_name": { "type": "string" },
			  "ending_cause_name_short": { "type": "string" },
			  "ending_cause_argo_ref": { "type": "string" },
			  "ending_cause_description": { "type": "string" }
			}
		  },
		  "retrieval_ship": { "$ref": "#/definitions/ship" },
		  "retrieval_cruise": { "$ref": "#/definitions/cruise" },
		  "retrieval_local_contact_info": { "type": "string" },
		  "retrieval_description": { "type": "string" },
		  "retrieval_ref_station_id": { "type": "string" }
		}
	  },
	  "platform_ancillary_device": {
		"type": "object",
		"properties": {
		  "device_model": { "type": "object" },
		  "device_version": { "type": "object" },
		  "device_serial_number": { "type": "string" }
		}
	  },
	  "platform_identifiers": {
		"type": "object",
		"properties": {
		  "platform_wmo_id": { "type": "string" },
		  "platform_serial_number": { "type": "string" },
		  "platform_internal_id": { "type": "string" },
		  "platform_wigos_id": { "type": "string" }
		}
	  },
	  "platform_telecoms": {
		"type": "array",
		"items": { "$ref": "#/definitions/telecom" }
	  },
	  "platform_sensors": {
		"type": "array",
		"items": { "$ref": "#/definitions/sensor" }
	  },
	  "platform_description": { "type": "string" },
	  "platform_ptf_software": {
		"type": "object",
		"properties": {
		  "type": { "type": "object" },
		  "name": { "type": "string" },
		  "version": { "type": "string" }
		}
	  },
	  "platform_software": {
		"type": "object",
		"properties": {
		  "name": { "type": "string" },
		  "version": { "type": "string" },
		  "format": { "type": "string" }
		}
	  },
	  "platform_firmware": {
		"type": "object",
		"properties": {
		  "name": { "type": "string" },
		  "serial_ref": { "type": "string" },
		  "bluetooth_id": { "type": "string" }
		}
	  },
	  "platform_hardware": {
		"type": "object",
		"properties": {
		  "battery": {
			"type": "object",
			"properties": {
			  "battery_id": { "type": "integer" },
			  "battery_name": { "type": "string" },
			  "battery_description": { "type": "string" },
			  "battery_ini_voltage": { "type": "integer" }
			}
		  },
		  "batteryPack": { "type": "string" },
		  "controlBoard": { "type": "string" },
		  "control_board_serial_number": { "type": "string" },
		  "manuf_date": { "type": "string" },
		  "batch_ref": { "type": "string" },
		  "has_drogue": { "type": "boolean" },
		  "special_feature": { "type": "string" }
		}
	  },
	  "platform_configuration": {
		"type": "object",
		"properties": {
		  "cycle_time": { "type": "string" },
		  "surface_time": { "type": "string" },
		  "drift_pressure": { "type": "string" },
		  "profile_pressure": { "type": "string" },
		  "automation_level": { "type": "object" },
		  "observation_schedule": { "type": "object" },
		  "inspection_interval": { "type": "string" },
		  "has_ice_detection_software": { "type": "boolean" }
		}
	  },
	  "platform_data": {
		"type": "object",
		"properties": {
		  "data_url": { "type": "string" },
		  "data_rtqc_method": { "type": "object" }
		}
	  },
	  "platform_weblinks": { "type": "array" },
	  "platform_agencies": {
		"type": "array",
		"items": { "$ref": "#/definitions/agency" }
	  },
	  "platform_statuses": {
		"type": "array",
		"items": { "$ref": "#/definitions/platform_status" }
	  },
	  "platform_sites": { "type": "array" },
	  "platform_latest_status": { "$ref": "#/definitions/platform_status" },
	  "platform_contributors": {
		"type": "array",
		"items": { "$ref": "#/definitions/contact" }
	  },
	  "platform_observations": {
		"type": "array",
		"items": { "$ref": "#/definitions/observation" }
	  },
	  "platform_locations": {
		"type": "array",
		"items": {
		  "type": "object",
		  "properties": {
			"location_date": { "type": "string", "format": "date-time" },
			"location_latitude": { "type": "number" },
			"location_longitude": { "type": "number" }
		  },
		  "required": ["location_date", "location_latitude", "location_longitude"]
		}
	  }
	},
	"required": ["platform_id", "platform_ref", "platform_program"],
	"definitions": {
	  "country": { "$ref": "country.schema.json" },
	  "ship": { "$ref": "ship.schema.json" },
	  "cruise": { "$ref": "cruise.schema.json" },
	  "platform_status": { "$ref": "platform_status.schema.json" },
	  "telecom": { "$ref": "telecom.schema.json" },
	  "agency": { "$ref": "agency.schema.json" },
	  "contact": { "$ref": "contact.schema.json" },
	  "observation": { "$ref": "observation.schema.json" },
	  "platform_model": { "$ref": "platform_model.schema.json" },
	  "network": { "$ref": "network.schema.json" },
	  "sensor": { "$ref": "sensor.schema.json" }
	}
  }

=== OceanOPS/oceanjson/examples/ptf-output-example.json
{
	"platform_id": 202343687,
	"platform_ref": "2955YIU",
	"platform_program": {
		"program_id": 5690,
		"program_name": "Argo INDIA",
		"program_description": "FY starts Apr 1 _ funded by Dept. of Ocean Development; implemented by National Center for Ocean Information Services (lead)",
		"program_country": {
			"country_code3": "IND",
			"country_code2": "IN",
			"country_name": "India",
			"country_id": 182
		},
		"program_name_short": "Argo_INDIA",
		"program_wigos_code": "argoIndia",
		"program_network": {
			"network_id": 1000620,
			"network_name": "Argo",
			"network_name_short": "Argo",
			"network_description": "Argo (GOOS/JCOMM)",
			"network_rank": 0,
			"network_wigos_code": "argo"
		}
	},
	"platform_project": "",
	"platform_site": {
		"site_id": 64,
		"site_name": "IMOS-POLYNYA",
		"site_description": "Polynya Array"
	},
	"platform_name": "",
	"platform_parent_ref": "",
	"platform_activity_criterion": 30,
	"platform_closure_criterion": 90,
	"platform_class_categories": [],
	"platform_area": [],
	"platform_services": [],
	"platform_networks": [],
	"platform_sub_networks": [],
	"platform_all_networks": [{
		"network_id": 1000420,
		"network_name": "Argo Core",
		"network_name_short": "ARGO_CORE",
		"network_description": "core T/S float funded under a regular national Argo program (without BGC sensors, not deep)",
		"network_rank": 1,
		"network_wigos_code": null,
		"parent_network": {
			"network_id": 1000620,
			"network_name": "Argo",
			"network_name_short": "Argo",
			"network_description": "Argo (GOOS/JCOMM)",
			"network_rank": 0,
			"network_wigos_code": "argo"
		}
	}],
	"platform_model": {
		"platform_model_id": 1208,
		"platform_model_name": "PAWS",
		"platform_model_name_short": "PAWS",
		"platform_model_description": "The MetOcean Polar Area Weather Station (PAWS) is a compact, rugged, and easy-to-use polar platform that provides quality-controlled data in harsh weather conditions.",
		"platform_model_total_height": 115.0,
		"platform_model_weight": 140,
		"platform_model_type": {
			"platform_type_id": 1000,
			"platform_type_name": "Float Deep",
			"platform_type_name_short": "FLOAT_DEEP",
			"platform_type_description": "Profiling float that is capable of profiling deeper than 2000dbar ",
			"platform_type_wigos_code": "underwaterMobile",
			"platform_family": {
				"platform_family_id": 2,
				"platform_family_name": "Subsurface Profiler",
				"platform_family_name_short": "SUB_P",
				"platform_family_description": "Subsurface profilers"
			}
		}
	},
	"platform_owner": {},
	"platform_service_schedule": {},
	"platform_principal_investigator": {},
	"platform_operating_agency": {},
	"platform_dac": {},
	"platform_end_date": "",
	"platform_deployment": {
		"deployment_method": {
			"method_id": 2,
			"method_name": "THROW_OVER",
			"method_description": "Instrument is manually thrown over into the water"
		},
		"deployment_country": {
			"country_code3": "DEU",
			"country_code2": "DE",
			"country_name": "Germany",
			"country_id": 164
		},
		"deployment_latitude": null,
		"deployment_longitude": null,
		"deployment_height": null,
		"deployment_date": "",
		"deployment_ship": {
            "ship_country": {
                "country_code3": "DEU",
                "country_code2": "DE",
                "country_name": "Germany",
                "country_id": 164
            },
            "ship_breadth": 20.6,
            "ship_length": 116,
            "ship_type_name": "Research Vessels",
            "ship_contacts_sea_email_1": "",
            "ship_imo": "9633927",
            "ship_call_sign": "DBBE",
            "ship_commissioned_date": "2014-08-11",
            "ship_contact_shore_email_1": "",
            "ship_contact_sea_email_3": "",
            "ship_ref": "06SN",
            "ship_contact_sea_email_2": "",
            "ship_draft": 6.5,
            "ship_name": "SONNE",
            "ship_type_id": 42,
            "ship_id": 1005245,
            "ship_contact_shore_email_3": "",
            "ship_contact_shore_email_2": ""
        },
		"deployment_cruise": {},
		"ref_station_id": "",
		"no_site": false,
		"max_mooring_depth": null,
		"deployment_operator": {}
	},
	"platform_retrieval": {
		"retrieval_status": {
			"status_id": 2,
			"status_name": "Recovered",
			"status_name_short": "RECOVERED"
		},
		"post_retrieval_status": {},
		"retrieval_latitude": null,
		"retrieval_longitude": null,
		"retrieval_start_date": "",
		"retrieval_end_date": "",
		"retrieval_country": {
			"country_code3": "DEU",
			"country_code2": "DE",
			"country_name": "Germany",
			"country_id": 164
		},
		"platform_ending_cause": {
			"ending_cause_id": 2,
			"ending_cause_name": "Beached platform",
			"ending_cause_name_short": "BEACHED",
			"ending_cause_argo_ref": "beached",
			"ending_cause_description": "The platform beached at the coastline"
		},
		"retrieval_ship": {
            "ship_country": {
                "country_code3": "DEU",
                "country_code2": "DE",
                "country_name": "Germany",
                "country_id": 164
            },
            "ship_breadth": 20.6,
            "ship_length": 116,
            "ship_type_name": "Research Vessels",
            "ship_contacts_sea_email": "",
            "ship_imo": "9633927",
            "ship_call_sign": "DBBE",
            "ship_commissioned_date": "2014-08-11",
            "ship_contact_shore_email_1": "",
            "ship_contact_sea_email_3": "",
            "ship_ref": "06SN",
            "ship_contact_sea_email_2": "",
            "ship_draft": 6.5,
            "ship_name": "SONNE",
            "ship_type_id": 42,
            "ship_id": 1005245,
            "ship_contact_shore_email_3": "",
            "ship_contact_shore_email_2": ""
        },
		"retrieval_cruise": {
			"cruise_id": null,
			"cruise_name": "",
			"cruise_ref": "",
			"cruise_iioe2_id": "",
			"cruise_mfp_id": "",
			"cruise_csr_id": "",
			"cruise_project_name": "",
			"cruise_start_date": "",
			"cruise_end_date": "",
			"cruise_arrival_port": {
				"port_country_code": "CU",
				"port_code": "CMW",
				"port_code_full": "CUCMW",
				"port_code_name": "Camag√ºey",
				"port_code_name_simple": "Camaguey"
			},
			"cruise_departure_port": {
				"port_country_code": "AU",
				"port_code": "SKA",
				"port_code_full": "AUSKA",
				"port_code_name": "Skardon River",
				"port_code_name_simple": "Skardon River"
			},
			"cruise_ship": {},
			"cruise_status": {
				"cruise_status_id": 25,
				"cruise_status_name": "Data Submitted",
				"cruise_status_description": "Delayed-Mode Data Submitted"
			},
			"cruise_lead_program": {},
			"cruise_type": {
				"cruise_type_id": 2,
				"cruise_type_name": "Civil Society",
				"cruise_type_name_short": "CIVIL_SOC"
			},
			"parent_cruise": {},
			"cruise_class": {
				"cruise_class_id": 1,
				"cruise_class_name": "GO-SHIP reference"
			},
			"cruise_other_programs": [],
			"cruise_contacts": [],
			"cruise_lines": [{
				"line_id": 1000132,
				"line_name": "I06S",
				"line_family": {
					"line_family_id": 1,
					"line_family_name": "GO-SHIP Line",
					"line_family_name_short": "GOSHIP_LINE"
				},
				"line_decadal_status": {
					"line_decadal_status_id": 5,
					"line_decadal_status_name": "Alarm",
					"line_decadal_status_description": "No cruise completed on line for more than 7 years, AND no cruise(s) [at sea or funded or planned] on line in next 4 years"
				}
			}],
			"cruise_countries": [],
			"cruise_sensor_models": [],
			"cruise_description": "",
			"cruise_performance_comment": "",
			"cruise_route_flexible": false,
			"cruise_route_pending": false,
			"cruise_route_private": false,
			"cruise_dates_pending": false,
			"cruise_ship_stop": false,
			"cruise_embark_capacity": null,
			"cruise_storage_capacity": null,
			"cruise_cost_unit": null,
			"cruise_cost_month": null
		},
		"retrieval_local_contact_info": "",
		"retrieval_description": "",
		"retrieval_ref_station_id": ""
	},
	"platform_ancillary_device": {
		"device_model": {},
		"device_version": {},
		"device_serial_number": ""
	},
	"platform_identifiers": {
		"platform_wmo_id": "",
		"platform_serial_number": "",
		"platform_internal_id": "",
		"platform_wigos_id": ""
	},
	"platform_telecoms": [{
			"telecom_type": {
				"telecom_type_id": 1000010,
				"telecom_type_name": "GLOBALSTAR",
				"telecom_type_description": "Globalstar communication system"
			},
			"telecom_service": {
				"telecom_service_id": 65,
				"telecom_service_name": "TURBOWIN",
				"telecom_service_description": "TurboWin Obs2Server"
			},
			"telecom_format": {
				"telecom_format_id": 1000005,
				"telecom_format_name": "TAC",
				"telecom_format_description": "Traditional Alphanumeric Code not leisted below"
			},
			"telecom_number": "6876672",
			"telecom_imei": "765765726576562",
			"telecom_latency": {
				"latency_id": 2,
				"latency_name": "NRT",
				"latency_name_short": "Near real-Time (< 20min)",
				"latency_minutes": 20
			},
			"telecom_tracking_system": {
				"tracking_system_id": 0,
				"tracking_system_name": "ARGOS DOPPLER",
				"tracking_system_name_short": "ARGOS",
				"tracking_system_wigos_code": "argosDoppler"
			},
			"telecom_is_backup": false
		},
		{
			"telecom_type": {
				"telecom_type_id": 1000060,
				"telecom_type_name": "CELLULAR",
				"telecom_type_description": "communication using terrestrial wireless networks (GSM, GPRS)"
			},
			"telecom_service": {
				"telecom_service_id": 75,
				"telecom_service_name": "INMARSAT_OTHER",
				"telecom_service_description": "Inmarsat other special access code"
			},
			"telecom_format": {
				"telecom_format_id": 1000006,
				"telecom_format_name": "#100",
				"telecom_format_description": "Binary data format developped by E-Surfmar for AWS"
			},
			"telecom_number": "376837333",
			"telecom_imei": "228029802980928",
			"telecom_latency": {},
			"telecom_tracking_system": {
				"tracking_system_id": 2,
				"tracking_system_name": "GPS",
